### ISSUE TITLE
Set up Fission Publish action for PRs and branches

### ISSUE THREAD

**Issue by bmann** [application-research/FIPs#1]
See https://github.com/application-research/FIPs/blob/master/.github/workflows/publish.yml

- needs to work on main as well as branches
- need to link it to a different key / account / app domain like eg. `fips-preview.fission.app` or similar

Going to get some help from @walkah on this.

**Comment by walkah** [comment]
@bmann just so I'm clear - you want `main` publishing to `fips.fission.app` and then all other PRs / branches publishing to `fips-preview.fission.app` ?  The only issue with that is that PRs will clobber each other (last  publish wins).  The other option is generating random app names per PR... that's relatively new and we don't have great reporting for the app name (yet)

**Comment by bmann** [comment]
@walkah this repo needs completely new URLs, since FIPs is used for the live site upstream. 

I fixed upstream for master already. 

I put Filecoin user in 1P with a key. So, new app like fips-design for main and fips-design-pr for this repo?

I don’t think this design repo will be super active so clobbering PRs is fine. 

Then we can see which of them make sense upstream. I also don’t see a bunch of overlapping PRs at this point but clobbering isn’t great.

**Comment by walkah** [comment]
@bmann looks like I don't have permission to push to this repo. want me to send you a yaml file?

**Comment by bmann** [comment]
Left this on the PR:

> @walkah I realize that we probably need to keep master clean and keep it synced with upstream, so that we can use this repo for design tweaks that we can PR back into upstream.
>
>Can you please make this work for eg a "design" branch, and set up auto pull of upstream master?
>
>Or suggest what the best setup is

**Comment by bmann** [comment]
Calling this closed, but need to take a look at master (linked to upstream), and design, so will file another issue clarifying.
